######################################
### Configure programming language ###
######################################
language: java

##################################
### Make sure using Oracle JDK ###
##################################
jdk:
  - oraclejdk11

###################################
### Disable Email notifications ###
###################################
notifications:
  email: false

###############
### Caching ###
###############
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

###########################
### Actual Build Script ###
###########################
script:
  - ./gradlew build
  - ./gradlew --scan -s
  - ./gradlew codeCoverageReport

##################
### Deployment ###
##################
deploy:
  provider: script
  script: ./gradlew publish
  on:
    branch: master
    tags: true
